### ISSUE TITLE
Ability to specify headers

### ISSUE THREAD

**Issue by devth** [clj-commons/tentacles#13]
If we can specify headers we can get support for things like GitHub's:

- [Text match metadata](https://developer.github.com/v3/search/#text-match-metadata)
- Developer preivew endpoints like [Search topics](https://developer.github.com/v3/search/#search-topics)

**Comment by rborer** [comment]
That would be a nice addition indeed. If I'm not mistaken (I quickly read the doc) the only header that needs to be modified is the `Accept` header, correct? It's probably better to only allow this specific header to be modified if true.

If you're willing to submit a PR I would be more than happy to review it :-)

**Comment by devth** [comment]
Yes, in this case we only need to be able to specify `Accept`, but I wonder if it's useful for an API lib such as this to let the consumer get at *any* underlying low level details (like headers). 🤔 

Might be able to PR something eventually (not this week).

**Comment by rborer** [comment]
I usually like to be on the safe side as allowing to modify any headers may alter github responses in unhandled ways, leading to hard to diagnose bugs.

But anyway, if you have time to look I let you decide, depending on the code change, if it's worth the effort to add some safety net or if allowing to modify any headers is simpler to implement :smiley: .
